packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - '@effect/atom-react@4.0.0-rc.110'
  - '@effect/platform-node-shared@4.0.0-rc.110'
  - '@effect/platform-node@4.0.0-rc.110'
  - '@effect/vitest@4.0.0-rc.110'
  - effect@4.0.0-rc.110
